services:
- type: pserv
  name: mysql
  plan: starter
  env: docker
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 4
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  
